parameters:
    flutchman_ez_migration_ui.migration_controller.class: Flutchman\eZMigrationAdminUiBundle\Controller\MigrationController
    flutchman_ez_migration_ui.menu_event_listener.class: Flutchman\eZMigrationAdminUiBundle\EventListener\MenuListener

services:
    # Controller
    flutchman_ez_migration_ui.migration_controller:
        class: "%flutchman_ez_migration_ui.migration_controller.class%"
        arguments:
            - "@translator"

    # Event Listener
    flutchman_ez_migration_ui.menu_event_listener:
        class: "%flutchman_ez_migration_ui.menu_event_listener.class%"
        tags:
            - {name: kernel.event_subscriber}
